### ISSUE TITLE
Modify the displayName for the WithPropsFromConext

### ISSUE THREAD

**Issue by abdulhannanali** [xaviervia/react-context-props#5]
The current `displayName` assigned to the `WtihPropsFromContext` makes it very hard to debug in React developer tools, as it causes major redundancy in the React components.

#### Suggesiton
According to the convention for wrapping the displayName of the component in Higher Order Component in the [official documentation](https://facebook.github.io/react/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging) , we should do 

```js
`WithPropsFromContext(Target.displayName || Target.name)`
```

instead of 

```js
Target.displayName || Target.name
```

 which won't cause the redundancy and will help in debugging.

Any suggestions or feedback is welcomed. If it's okay, to do, I can go ahead and make a PR.

**Comment by abdulhannanali** [comment]
Here's an image of what happens right now 

![screenshot from 2017-05-31 20-37-10](https://cloud.githubusercontent.com/assets/8170969/26643389/9c621ed2-464a-11e7-9ec3-373befb1d37f.png)

**Comment by xaviervia** [comment]
True this. I've been moving to using [recompose’s wrapDisplayName](https://github.com/acdlite/recompose/blob/master/docs/API.md#wrapdisplayname) for this. I will update this lib with that change.
